apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- github.com/redhat-cop/gitops-catalog/cert-manager-operator/operator/base?ref=main
- default-ingress-certificate.yaml
- acme-cluster-issuer.yaml
generators:
- secret-generator.yaml
patchesStrategicMerge:
# equivalent command: oc patch ingresscontroller.operator default --type=merge -p '{"spec":{"defaultCertificate": {"name": "default-ingress-certificate"}}}' -n openshift-ingress-operator
- |-
  apiVersion: operator.openshift.io/v1
  kind: IngressController
  metadata:
    name: default
    namespace: openshift-ingress-operator
  spec:
    defaultCertificate:
      name: default-ingress-certificate
